const SUB_TITLE_COLOR = '#8E8E8E';
const CONTAINER_REVIEWTICKET_COLOR = '#FFEED2';
const INFO_TICKET_COLOR = '#454545';
const TOTAL_PRICE = '#898989';

export { SUB_TITLE_COLOR, CONTAINER_REVIEWTICKET_COLOR, INFO_TICKET_COLOR, TOTAL_PRICE };
